### ISSUE TITLE
Add fish-food for all apps in thecasualcoder

### ISSUE THREAD

**Issue by karuppiah7890** [thecasualcoder/homebrew-stable#3]
Similar to brew formula, add fish food for all the apps in casual coder in a separate repo. Similar to https://github.com/fishworks/fish-food

If a repo is created, I'm willing to create a PR for this. Starting with fish food for kube-fzf

**Comment by jskswamy** [comment]
@karuppiah7890 I've created the repo for [fish-food](https://github.com/thecasualcoder/fish-food)

**Comment by karuppiah7890** [comment]
Cool! Will raise PR for kube-fzf soon!
